### ISSUE TITLE
內嵌的 latex 公式不能正常顯示啊

### ISSUE THREAD

**Issue by shelper** [exacity/simplified-deeplearning#11]
例如附圖，試了 chrome 和 firefox 都是這樣子。。。
莫非需要裝什麼的插件？
![image](https://user-images.githubusercontent.com/546163/30336353-eaa0d14c-97b2-11e7-8693-9c21276f97fe.png)

頁面網址 https://exacity.github.io/deeplearningbook-chinese/Chapter2_linear_algebra/

**Comment by shelper** [comment]
看見其他相關的issue了

**Comment by Cauchyzhou** [comment]
怎么解决的啊？求助
