### ISSUE TITLE
深度网络 dropout 案例添加 

### ISSUE THREAD

**Issue by daweicheng** [exacity/simplified-deeplearning#13]
寻求 深度网络 drop 案例添加 
如何贡献代码参考 https://github.com/exacity/simplified-deeplearning/blob/master/pending/README.md

**Comment by hjptriplebee** [comment]
dropout案例？

**Comment by daweicheng** [comment]
是的，输入层或者隐含层添加dropout的网络案例，使用Tensorflow来写。

**Comment by hjptriplebee** [comment]
hjptriplebee@c3e58e01570a375da309097bf164ea8fb6e68062
